name: receivables

services:
  postgres:
    image: postgres:16-alpine
    container_name: receivables-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: receivables
      POSTGRES_PASSWORD: receivables_secret
      POSTGRES_DB: receivables_db
    ports:
      - '5436:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U receivables -d receivables_db']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: receivables-redis
    restart: unless-stopped
    ports:
      - '6381:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: receivables-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: receivables_minio_admin
      MINIO_ROOT_PASSWORD: receivables_minio_secret
    ports:
      - '9004:9000'
      - '9005:9001'
    volumes:
      - minio_data:/data

  minio-init:
    image: minio/mc:latest
    container_name: receivables-minio-init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 3;
      /usr/bin/mc alias set myminio http://minio:9000 receivables_minio_admin receivables_minio_secret;
      /usr/bin/mc mb myminio/receivables-documents --ignore-existing;
      /usr/bin/mc anonymous set download myminio/receivables-documents;
      exit 0;
      "

volumes:
  postgres_data:
  redis_data:
  minio_data:
